version: "4"

services:
  db:
    container_name: database-bet
    image: postgres:latest
    restart: always
    env_file:
      - ./server/.env
    # volumes:
    # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - ./server/.env
    # GUNICORN_ACCESS_LOGFILE: "/dev/null"
    ports:
      - 8080:80
    # volumes:
    #   - ./db/servers.json:/pgadmin4/servers.json
    logging:
      driver: none
    depends_on:
      - db
# networks:
#   client:
#     build: ./client
#     container_name: front-bet
#     environment:
#       - NODE_PATH=src
#       - CHOKIDAR_USEPOLLING=true
#     ports:
#       - 3000:3000
#     volumes:
#       - ./client/src:/app/src
#     links:
#       - server
#     extra-hosts:
#       - "host.docker.internal:host-gateway"
#     command: bun run dev

#   server:
#     build: ./server
#     container_name: back-bet
#     depends_on:
#       - db
#     env_file:
#       - ./server/.env
#     environment:
#       WAIT_HOSTS: db:5432
#     ports:
#       - 3001:3001
#     volumes:
#       - /app/node_modules
#       - ./server:/app
#     command: npm run dev
#     restart: on-failure

#   default:
#     name: betting-network
