services:
  postgres:
    container_name: database
    image: postgres:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./src/utils/db/init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    depends_on:
      - postgres
    ports:
      - "${PG_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_MAINTENANCE=${DB_MAINTENANCE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./src/utils/db/config/servers.template.json:/tmp/servers.template.json
      - ./data/pgadmin:/var/lib/pgadmin
    restart: unless-stopped
