name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend dependencies
        run: cd client && bun install

      - name: Run frontend tests
        run: cd client && bun run test

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_TEST_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install backend dependencies
        run: cd server && bun install
      - name: Run backend tests
        run: cd server && bun run test
        env:
          PORT: 3000
          DB_NAME: ${{ secrets.DB_TEST_NAME }}
          DB_PORT: 5432
          DB_LOCAL: localhost
          DB_HOST: postgres
          DB_MAINTENANCE: postgres
          DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
          PGADMIN_DEFAULT_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PG_PORT: 5050
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.POSTGRES_PASSWORD }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}